// Generated by BUCKLESCRIPT VERSION 4.0.7, PLEASE EDIT WITH CARE
'use strict';


function foo(x) {
  return x;
}

var A = /* module */[/* foo */foo];

var N = /* module */[/* foo */foo];

function testConversion(x) {
  return x;
}

var M = A;

var n = N;

var O = N;

exports.A = A;
exports.M = M;
exports.N = N;
exports.testConversion = testConversion;
exports.n = n;
exports.O = O;
/* No side effect */
