// Generated by BUCKLESCRIPT VERSION 4.0.6, PLEASE EDIT WITH CARE
'use strict';


function Make() {
  var Inner = /* module */[];
  return /* module */[/* Inner */Inner];
}

var A = /* module */[/* Make */Make];

var Inner = /* module */[];

var B = /* module */[/* Inner */Inner];

var Inner$1 = /* module */[];

var C = /* module */[/* Inner */Inner$1];

exports.A = A;
exports.B = B;
exports.C = C;
/* No side effect */
