// Generated by BUCKLESCRIPT VERSION 4.0.6, PLEASE EDIT WITH CARE
'use strict';


function testConversion(x) {
  return x;
}

var A = /* module */[];

exports.testConversion = testConversion;
exports.A = A;
/* No side effect */
