/**
 * This is file generated by genFlow. Do not modify.
 *
 * @flow strict
 * @nolint
 */

// Generated by BUCKLESCRIPT VERSION 4.0.0, PLEASE EDIT WITH CARE
'use strict';

var Component1 = require("../Component1.bs.js");
var ReasonReact = require("reason-react/src/ReasonReact.js");

import type {ComponentSpec as ReasonReactComponentSpec} from '../shims/ReasonReactFlowShim'
;

import type {Stateless as ReasonReactStateless} from '../shims/ReasonReactFlowShim'
;

import type {NoRetainedProps as ReasonReactNoRetainedProps} from '../shims/ReasonReactFlowShim'
;

import type {Actionless as ReasonReactActionless} from '../shims/ReasonReactFlowShim'
;

import type {Component as ReactComponent} from 'React'
;

export type Props = {|message:string|}
;

var component = ReasonReact.wrapReasonForJs(Component1.component, (function (jsProps) {
        var argB = jsProps.children;
        return Component1.make(jsProps.message, argB);
      }));

var __flowTypeValueAnnotation__component = "React$ComponentType<Props>";

exports.__flowTypeValueAnnotation__component = __flowTypeValueAnnotation__component;
exports.component = component;
/*  Not a pure module */
