// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE

import * as Curry from "bs-platform/lib/es6/curry.js";
import * as React from "react";
import * as Caml_array from "bs-platform/lib/es6/caml_array.js";
import * as ReasonReact from "reason-react/src/ReasonReact.js";

var component = ReasonReact.statelessComponent("App");

function make(array, $staropt$star, person, title, _children) {
  var callback = $staropt$star !== undefined ? $staropt$star : (function (param) {
        return /* () */0;
      });
  return {
          debugName: component.debugName,
          reactClassInternal: component.reactClassInternal,
          handedOffState: component.handedOffState,
          willReceiveProps: component.willReceiveProps,
          didMount: component.didMount,
          didUpdate: component.didUpdate,
          willUnmount: component.willUnmount,
          willUpdate: component.willUpdate,
          shouldUpdate: component.shouldUpdate,
          render: (function (_self) {
              Curry._1(callback, /* () */0);
              return React.createElement("div", undefined, "Test Component Title:" + (title + (" Name:" + (person.name + (" array[0]:" + Caml_array.caml_array_get(array, 0))))));
            }),
          initialState: component.initialState,
          retainedProps: component.retainedProps,
          reducer: component.reducer,
          jsElementWrapped: component.jsElementWrapped
        };
}

function poly(x, _y) {
  return x + 1 | 0;
}

export {
  component ,
  make ,
  poly ,
  
}
/* component Not a pure module */
