/* Untyped file generated by genType. */

import * as HooksBS from './Hooks.bs';

export const $$default = function Hooks(Arg1) {
  const result = HooksBS.default({vehicle:[Arg1.vehicle.name]});
  return result
};

export default $$default;
