// Generated by BUCKLESCRIPT VERSION 4.0.14, PLEASE EDIT WITH CARE
'use strict';

var Caml_option = require("bs-platform/lib/js/caml_option.js");
var ImportMyBannerGen = require("./ImportMyBanner.gen");

function make(prim, prim$1, prim$2) {
  return ImportMyBannerGen.make(prim, prim$1 !== undefined ? Caml_option.valFromOption(prim$1) : undefined, prim$2);
}

exports.make = make;
/* ./ImportMyBanner.gen Not a pure module */
