// Generated by BUCKLESCRIPT VERSION 4.0.6, PLEASE EDIT WITH CARE
'use strict';

var ReasonReact = require("reason-react/src/ReasonReact.js");

var component = ReasonReact.statelessComponent("RenameProps");

function functionWithGenTypeAs(firstNameArgumentCantBeRenamed, type_, number) {
  return firstNameArgumentCantBeRenamed + (type_ + String(number));
}

function make(firstNameArgumentCantBeRenamed, type_, number, _) {
  return /* record */[
          /* debugName */component[/* debugName */0],
          /* reactClassInternal */component[/* reactClassInternal */1],
          /* handedOffState */component[/* handedOffState */2],
          /* willReceiveProps */component[/* willReceiveProps */3],
          /* didMount */component[/* didMount */4],
          /* didUpdate */component[/* didUpdate */5],
          /* willUnmount */component[/* willUnmount */6],
          /* willUpdate */component[/* willUpdate */7],
          /* shouldUpdate */component[/* shouldUpdate */8],
          /* render */(function () {
              return firstNameArgumentCantBeRenamed + (type_ + String(number));
            }),
          /* initialState */component[/* initialState */10],
          /* retainedProps */component[/* retainedProps */11],
          /* reducer */component[/* reducer */12],
          /* jsElementWrapped */component[/* jsElementWrapped */13]
        ];
}

function firstIsIgnored(x) {
  return x + 0 | 0;
}

function padding1(pad, x) {
  return pad + x | 0;
}

function padding2(pad, x) {
  return pad + x | 0;
}

function padding3(pad1, pad2, x) {
  return (pad1 + pad2 | 0) + x | 0;
}

function renameABunch(pad, x, y, z) {
  return ((pad + x | 0) + y | 0) + z | 0;
}

function renameABunch2(pad, x, y, z) {
  return ((pad + x | 0) + y | 0) + z | 0;
}

function renameABunch3(pad, x, y, z) {
  return ((pad + x | 0) + y | 0) + z | 0;
}

exports.component = component;
exports.functionWithGenTypeAs = functionWithGenTypeAs;
exports.make = make;
exports.firstIsIgnored = firstIsIgnored;
exports.padding1 = padding1;
exports.padding2 = padding2;
exports.padding3 = padding3;
exports.renameABunch = renameABunch;
exports.renameABunch2 = renameABunch2;
exports.renameABunch3 = renameABunch3;
/* component Not a pure module */
