// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var ImportHookDefaultGen = require("./ImportHookDefault.gen").default;
var ImportHookDefaultGen$1 = require("./ImportHookDefault.gen");

var make = ImportHookDefaultGen$1.make;

var make2 = ImportHookDefaultGen;

exports.make = make;
exports.make2 = make2;
/* make Not a pure module */
