// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';

var ImportValuesGen = require("./ImportValues.gen");

var exportValues = ImportValuesGen.exportValues;

var innerStuffContents = ImportValuesGen.innerStuffContents;

exports.exportValues = exportValues;
exports.innerStuffContents = innerStuffContents;
/* exportValues Not a pure module */
