// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';

var ImportMyBannerGen = require("./ImportMyBanner.gen");

function make(prim, prim$1, prim$2) {
  return ImportMyBannerGen.make(prim, prim$1, prim$2);
}

exports.make = make;
/* ./ImportMyBanner.gen Not a pure module */
