// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';


var Inner = {
  x: 34,
  y: "hello"
};

var Inner$1 = {
  y: 44
};

var Medium = {
  Inner: Inner$1
};

var Outer = {
  Medium: Medium
};

exports.Inner = Inner;
exports.Outer = Outer;
/* No side effect */
