// Generated by BUCKLESCRIPT VERSION 5.0.0-dev.5, PLEASE EDIT WITH CARE

import * as ImportMyBannerGen from "./ImportMyBanner.gen";

function make(prim, prim$1, prim$2) {
  return ImportMyBannerGen.make(prim, prim$1, prim$2);
}

export {
  make ,
  
}
/* ./ImportMyBanner.gen Not a pure module */
