// Generated by BUCKLESCRIPT VERSION 4.0.7, PLEASE EDIT WITH CARE

import * as ImportJsValueGen from "./ImportJsValue.gen";

function myArea(prim) {
  return ImportJsValueGen.area(prim);
}

var roundedNumber = ImportJsValueGen.round(1.8);

var areaValue = ImportJsValueGen.area(/* record */[
      /* x */3,
      /* y */undefined
    ]);

export {
  myArea ,
  roundedNumber ,
  areaValue ,
  
}
/* roundedNumber Not a pure module */
