/* TypeScript file generated by genType. */
/* eslint-disable import/first */


// tslint:disable-next-line:interface-over-type-literal
export type someMutableFields = {
  mutable0: string; 
  readonly immutable: number; 
  mutable1: string; 
  mutable2: string
};
