// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE

import * as ErrorHandler from "./ErrorHandler.bs.js";

function notification(param) {
  return /* tuple */[
          "",
          ""
        ];
}

var Error2 = {
  notification: notification
};

var MyErrorHandler = ErrorHandler.Make(Error2);

export {
  Error2 ,
  MyErrorHandler ,
  
}
/* MyErrorHandler Not a pure module */
