// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE

import * as ImmutableArray from "./ImmutableArray.bs.js";

console.log(ImmutableArray.fromArray);

var Inner = { };

var M = { };

var fortytwo = 42;

var fortyTwoButExported = 42;

var thisIsUsedOnce = 34;

var thisIsUsedTwice = 34;

var thisIsKeptAlive = 42;

var thisIsMarkedLive = 42;

export {
  fortytwo ,
  fortyTwoButExported ,
  thisIsUsedOnce ,
  thisIsUsedTwice ,
  thisIsKeptAlive ,
  thisIsMarkedLive ,
  Inner ,
  M ,
  
}
/*  Not a pure module */
