// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE

import * as ImmutableArray from "./ImmutableArray.bs.js";

console.log(ImmutableArray.fromArray);

var fortytwo = 42;

var fortyTwoButExported = 42;

var thisIsUsedOnce = 34;

var thisIsUsedTwice = 34;

export {
  fortytwo ,
  fortyTwoButExported ,
  thisIsUsedOnce ,
  thisIsUsedTwice ,
  
}
/*  Not a pure module */
