// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE

import * as DeadValueTest from "./DeadValueTest.bs.js";
import * as ImmutableArray from "./ImmutableArray.bs.js";

console.log(ImmutableArray.fromArray);

var Inner = { };

var M = { };

var VariantUsedOnlyInImplementation = {
  a: /* A */0
};

var UnderscoreInside = { };

var MM = {
  x: 55,
  y: 55
};

console.log(55);

console.log(DeadValueTest.valueAlive);

function unusedRec(_param) {
  while(true) {
    _param = /* () */0;
    continue ;
  };
}

function split_map(l) {
  split_map(l);
  return /* [] */0;
}

function rec1(_param) {
  while(true) {
    _param = /* () */0;
    continue ;
  };
}

function rec2(_param) {
  while(true) {
    _param = /* () */0;
    continue ;
  };
}

var fortytwo = 42;

var fortyTwoButExported = 42;

var thisIsUsedOnce = 34;

var thisIsUsedTwice = 34;

var thisIsKeptAlive = 42;

var thisIsMarkedLive = 42;

export {
  fortytwo ,
  fortyTwoButExported ,
  thisIsUsedOnce ,
  thisIsUsedTwice ,
  thisIsKeptAlive ,
  thisIsMarkedLive ,
  Inner ,
  M ,
  VariantUsedOnlyInImplementation ,
  UnderscoreInside ,
  MM ,
  unusedRec ,
  split_map ,
  rec1 ,
  rec2 ,
  
}
/*  Not a pure module */
