// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE


function thisSpansSeveralLines(x, y) {
  return x + y | 0;
}

var QQ = {
  thisSpansSeveralLines: thisSpansSeveralLines
};

function thisIsInInterface(x) {
  return x;
}

var AA = {
  thisIsInInterface: thisIsInInterface
};

var Bs_version = {
  version: "7.2.0-dev.4",
  header: "// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE",
  package_name: "bs-platform"
};

var thisHasSemicolons = 3;

export {
  QQ ,
  AA ,
  thisHasSemicolons ,
  Bs_version ,
  
}
/* No side effect */
