// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE


function thisSpansSeveralLines(x, y) {
  return x + y | 0;
}

var QQ = {
  thisSpansSeveralLines: thisSpansSeveralLines
};

function thisIsInInterface(x) {
  return x;
}

var AA = {
  thisIsInInterface: thisIsInInterface
};

var thisHasSemicolons = 3;

export {
  QQ ,
  AA ,
  thisHasSemicolons ,
  
}
/* No side effect */
