// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE


function foo(t) {
  if (t) {
    console.log("B" + t[/* name */0]);
    return ;
  } else {
    console.log("A");
    return ;
  }
}

var X = {
  foo: foo,
  x: 42
};

var Y = {
  x: ""
};

export {
  X ,
  Y ,
  
}
/* No side effect */
