// Generated by BUCKLESCRIPT VERSION 4.0.14, PLEASE EDIT WITH CARE


function testWithPayload(x) {
  return x;
}

function printEnumValue(x) {
  if (typeof x === "number") {
    if (x !== 97) {
      if (x >= 803296723) {
        if (x >= 937218926) {
          console.log("printEnumValue: True");
          return /* () */0;
        } else {
          console.log("printEnumValue: Half");
          return /* () */0;
        }
      } else if (x >= 98) {
        console.log("printEnumValue: b");
        return /* () */0;
      } else {
        console.log("printEnumValue: Twenty");
        return /* () */0;
      }
    } else {
      console.log("printEnumValue: a");
      return /* () */0;
    }
  } else {
    var payload = x[1];
    console.log("printEnumValue x:", payload[/* x */0], "y:", payload[/* y */1]);
    return /* () */0;
  }
}

function testManyPayloads(x) {
  return x;
}

function printManyPayloads(x) {
  var variant = x[0];
  if (variant !== 5795212) {
    if (variant >= 261117022) {
      var payload = x[1];
      console.log("printManyPayloads x:", payload[/* x */0], "y:", payload[/* y */1]);
      return /* () */0;
    } else {
      console.log("printManyPayloads one:", x[1]);
      return /* () */0;
    }
  } else {
    var match = x[1];
    console.log("printManyPayloads two:", match[0], match[1]);
    return /* () */0;
  }
}

function testSimpleVariant(x) {
  return x;
}

export {
  testWithPayload ,
  printEnumValue ,
  testManyPayloads ,
  printManyPayloads ,
  testSimpleVariant ,
  
}
/* No side effect */
