// Generated by BUCKLESCRIPT VERSION 5.0.2, PLEASE EDIT WITH CARE


var y = "abc";

var EmptyInnerModule = /* module */[];

var InnerModule2 = /* module */[/* k */4242];

function k3(x) {
  return x + 1 | 0;
}

var InnerModule3 = /* module */[/* k3 */k3];

var Z = /* module */[/* u : tuple */[
    0,
    0
  ]];

var M = /* module */[
  /* y */y,
  /* EmptyInnerModule */EmptyInnerModule,
  /* InnerModule2 */InnerModule2,
  /* InnerModule3 */InnerModule3,
  /* Z */Z,
  /* x */42
];

var firstClassModule = [
  42,
  EmptyInnerModule,
  InnerModule2,
  InnerModule3,
  Z,
  y
];

function testConvert(m) {
  return m;
}

function SomeFunctor(X) {
  var ww = X[/* y */5];
  return /* module */[/* ww */ww];
}

function someFunctorAsFunction(x) {
  var ww = x[/* y */5];
  return /* module */[/* ww */ww];
}

export {
  M ,
  firstClassModule ,
  testConvert ,
  SomeFunctor ,
  someFunctorAsFunction ,
  
}
/* No side effect */
