/* TypeScript file generated by genType. */

// tslint:disable-next-line:no-var-requires
const HooksBS = require('./Hooks.bs');

import {reactElement as ReasonReact_reactElement} from '../src/shims/ReactShim.shim';

// tslint:disable-next-line:interface-over-type-literal
export type vehicle = { readonly name: string };

export const make: (_1:{ readonly vehicle: vehicle }) => ReasonReact_reactElement = function (Arg1: any) {
  const result = HooksBS.make({vehicle:[Arg1.vehicle.name]});
  return result
};
