// Generated by BUCKLESCRIPT VERSION 5.0.2, PLEASE EDIT WITH CARE

import * as ImportHoooksGen from "./ImportHoooks.gen";

var make = ImportHoooksGen.make;

function foo(prim) {
  return ImportHoooksGen.foo(prim);
}

export {
  make ,
  foo ,
  
}
/* make Not a pure module */
