// Generated by BUCKLESCRIPT VERSION 5.0.6, PLEASE EDIT WITH CARE

import * as ImportHooksGen from "./ImportHooks.gen";

var make = ImportHooksGen.makeRenamed;

function foo(prim) {
  return ImportHooksGen.foo(prim);
}

export {
  make ,
  foo ,
  
}
/* make Not a pure module */
