// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE

import * as ImportHookDefaultGen from "./ImportHookDefault.gen";

var make = ImportHookDefaultGen.make;

var make2 = ImportHookDefaultGen.default;

export {
  make ,
  make2 ,
  
}
/* make Not a pure module */
