// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE

import * as ImmutableArray from "./ImmutableArray.bs.js";

console.log(ImmutableArray.fromArray);

var fortytwo = 42;

export {
  fortytwo ,
  
}
/*  Not a pure module */
