// Generated by BUCKLESCRIPT VERSION 5.0.2, PLEASE EDIT WITH CARE


var Inner = /* module */[];

var Outer = /* module */[/* Inner */Inner];

var OuterAlias = 0;

var InnerAlias = 0;

var q = 42;

export {
  Outer ,
  OuterAlias ,
  InnerAlias ,
  q ,
  
}
/* No side effect */
