// Generated by BUCKLESCRIPT VERSION 5.0.2, PLEASE EDIT WITH CARE


var Inner = /* module */[];

var Outer = /* module */[/* Inner */Inner];

var InnerNested = /* module */[];

var Inner2 = /* module */[
  /* InnerNested */InnerNested,
  /* OuterInnerAlias2 */0
];

var Outer2 = /* module */[
  /* OuterInnerAlias */0,
  /* Inner2 */Inner2
];

function testNested(x) {
  return x;
}

function testInner(x) {
  return x;
}

function testInner2(x) {
  return x;
}

var Outer2Alias = 0;

var InnerNestedAlias = 0;

export {
  Outer ,
  Outer2 ,
  Outer2Alias ,
  InnerNestedAlias ,
  testNested ,
  testInner ,
  testInner2 ,
  
}
/* No side effect */
