// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE


var Inner = { };

var Outer = {
  Inner: Inner
};

var InnerNested = { };

var Inner2 = {
  InnerNested: InnerNested,
  OuterInnerAlias2: /* alias */0
};

var Outer2 = {
  OuterInnerAlias: /* alias */0,
  Inner2: Inner2
};

function testNested(x) {
  return x;
}

function testInner(x) {
  return x;
}

function testInner2(x) {
  return x;
}

var Outer2Alias = /* alias */0;

var InnerNestedAlias = /* alias */0;

export {
  Outer ,
  Outer2 ,
  Outer2Alias ,
  InnerNestedAlias ,
  testNested ,
  testInner ,
  testInner2 ,
  
}
/* No side effect */
