// Generated by BUCKLESCRIPT VERSION 4.0.6, PLEASE EDIT WITH CARE
'use strict';

var Js_primitive = require("bs-platform/lib/js/js_primitive.js");
var MyBannerWrapper = require("./MyBannerWrapper");

function make(prim, prim$1, prim$2) {
  return MyBannerWrapper.make(prim, prim$1 !== undefined ? Js_primitive.valFromOption(prim$1) : undefined, prim$2);
}

exports.make = make;
/* ./MyBannerWrapper Not a pure module */
