/* TypeScript file generated by genType. */

// tslint:disable-next-line:no-var-requires
const NestedModulesInSignatureBS = require('./NestedModulesInSignature.bs');

export const Universe_theAnswer: number = NestedModulesInSignatureBS.Universe[0];
