/* TypeScript file generated by genType. */
/* eslint-disable import/first */


// tslint:disable-next-line:no-var-requires
const NestedModulesInSignatureBS = require('./NestedModulesInSignature.bs');

export const Universe_theAnswer: number = NestedModulesInSignatureBS.Universe.theAnswer;
