/* Typescript file generated by genType. */

// tslint:disable-next-line:no-var-requires
const NestedModulesInSignatureBS = require('./NestedModulesInSignature.bs');

export const theAnswer: number = NestedModulesInSignatureBS.theAnswer;
