/* TypeScript file generated by genType. */

// tslint:disable-next-line:no-var-requires
import * as NestedModulesInSignatureBS from './NestedModulesInSignature.bs';

export const Universe_theAnswer: number = NestedModulesInSignatureBS.Universe[0];
