/* TypeScript file generated by genType. */
/* eslint-disable import/first */


// tslint:disable-next-line:no-var-requires
const TestEmitInnerModulesBS = require('./TestEmitInnerModules.bs');

export const Inner_x: number = TestEmitInnerModulesBS.Inner.x;

export const Inner_y: string = TestEmitInnerModulesBS.Inner.y;

export const Outer_Medium_Inner_y: number = TestEmitInnerModulesBS.Outer.Medium.Inner.y;

export const Inner: { x: number; y: string } = { x: Inner_x, y: Inner_y }

export const Outer: { Medium: { Inner: { y: number } } } = { Medium: { Inner: { y: Outer_Medium_Inner_y } } }
