// Generated by BUCKLESCRIPT VERSION 6.0.0-dev.1, PLEASE EDIT WITH CARE


function convert(param) {
  return param.then((function (param) {
                return Promise.resolve(/* record */[/* result */param[/* s */1]]);
              }));
}

export {
  convert ,
  
}
/* No side effect */
