// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE

import * as Curry from "bs-platform/lib/es6/curry.js";
import * as Caml_obj from "bs-platform/lib/es6/caml_obj.js";

function progress(param) {
  return /* () */0;
}

function fox(x) {
  while(true) {
    Caml_obj.caml_notequal(x, x);
    fox(x);
    continue ;
  };
}

function box(x) {
  fox(x);
  return fox(x);
}

function takeParseFunction(x, parseFunction) {
  return Curry._1(parseFunction, x);
}

var b = 4;

var a = 3;

export {
  progress ,
  fox ,
  box ,
  takeParseFunction ,
  a ,
  b ,
  
}
/* No side effect */
