// Generated by BUCKLESCRIPT VERSION 5.0.0-dev.6, PLEASE EDIT WITH CARE


function convert(x) {
  return x;
}

function convertInterface(x) {
  return x;
}

function convertRecord(x) {
  return x;
}

function convertFirstClassModuleWithTypeEquations(x) {
  return x;
}

export {
  convert ,
  convertInterface ,
  convertRecord ,
  convertFirstClassModuleWithTypeEquations ,
  
}
/* No side effect */
