// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE

import * as ImmutableArray from "./ImmutableArray.bs.js";

function testImmutableArrayGet(arr) {
  return ImmutableArray.$$Array.get(arr, 3);
}

export {
  testImmutableArrayGet ,
  
}
/* No side effect */
