/* TypeScript file generated by genType. */

// tslint:disable-next-line:no-var-requires
const TestImmutableArrayBS = require('./TestImmutableArray.bs');

export const testImmutableArrayGet: <T1>(_1:ReadonlyArray<T1>) => (null | undefined | T1) = TestImmutableArrayBS.testImmutableArrayGet;
