/* Typescript file generated by genType. */

// BEGIN: added by hand
// tslint:disable-next-line:no-var-requires
const MyMath = require("./MyMath");

export const round = function _(x: number): number {
  return MyMath.round(x);
};
// END: added by hand

// tslint:disable-next-line:no-var-requires
const TestBS = require("./Test.bs");

export const roundedNumber: number = TestBS.roundedNumber;
