/* Typescript file generated by genType. */

// tslint:disable-next-line:no-var-requires
const MyMath = require("./MyMath");

export const round: (_1:number) => number = MyMath.round;

// tslint:disable-next-line:no-var-requires
const TestBS = require("./Test.bs");

export const roundedNumber: number = TestBS.roundedNumber;
