// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE

import * as Curry from "bs-platform/lib/es6/curry.js";
import * as Caml_obj from "bs-platform/lib/es6/caml_obj.js";

function progress(param) {
  return /* () */0;
}

function fox(x) {
  while(true) {
    Caml_obj.caml_notequal(x, x);
    continue ;
  };
}

var box = fox;

function takeParseFunction(x, parseFunction) {
  return Curry._1(parseFunction, x);
}

var Loops = {
  fox: fox,
  box: box,
  takeParseFunction: takeParseFunction
};

function fox2(x) {
  while(true) {
    Caml_obj.caml_notequal(x, x);
    fox2(x);
    continue ;
  };
}

function box2(x) {
  fox2(x);
  return fox2(x);
}

function takeParseFunction2(x, parseFunction) {
  return Curry._1(parseFunction, x);
}

function aa(x) {
  while(true) {
    x > 0;
    continue ;
  };
}

var bb = aa;

function cc(param) {
  return /* () */0;
}

var Terminates = {
  fox2: fox2,
  box2: box2,
  takeParseFunction2: takeParseFunction2,
  u: /* () */0,
  aa: aa,
  bb: bb,
  cc: cc
};

var b = 4;

var a = 3;

export {
  progress ,
  Loops ,
  Terminates ,
  a ,
  b ,
  
}
/* No side effect */
