// Generated by BUCKLESCRIPT VERSION 4.0.12, PLEASE EDIT WITH CARE

import * as TestImportGen from "./TestImport.gen";

var innerStuffContents = TestImportGen.innerStuffContents;

export {
  innerStuffContents ,
  
}
/* innerStuffContents Not a pure module */
