// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE


function fox(x) {
  while(true) {
    continue ;
  };
}

function box(x) {
  while(true) {
    continue ;
  };
}

var b = 4;

var a = 3;

export {
  fox ,
  box ,
  a ,
  b ,
  
}
/* No side effect */
