/* TypeScript file generated by genType. */
/* eslint-disable import/first */


// tslint:disable-next-line:no-var-requires
const TestEmitInnerModulesBS = require('./TestEmitInnerModules.bs');

export const Inner_x: number = TestEmitInnerModulesBS.Inner[0];

export const Inner_y: string = TestEmitInnerModulesBS.Inner[1];

export const Outer_Medium_Inner_y: number = TestEmitInnerModulesBS.Outer[0][0][0];
