// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Caml_obj from "rescript/lib/es6/caml_obj.js";
import * as Caml_option from "rescript/lib/es6/caml_option.js";

function convert(param) {
  return param.then(function (param) {
              return Promise.resolve({
                          result: param.s
                        });
            });
}

function barx(xOpt, param) {
  var x = xOpt !== undefined ? Caml_option.valFromOption(xOpt) : Promise.resolve("a");
  return Caml_obj.caml_equal(x, x);
}

export {
  convert ,
  barx ,
  
}
/* No side effect */
