// Generated by BUCKLESCRIPT VERSION 5.0.6, PLEASE EDIT WITH CARE


function convert(x) {
  return x;
}

function convertAlias(x) {
  return x;
}

export {
  convert ,
  convertAlias ,
  
}
/* No side effect */
