/* TypeScript file generated by genType. */

// tslint:disable-next-line:no-var-requires
const TransitiveType2BS = require('./TransitiveType2.bs');

import {t3 as TransitiveType3_t3} from './TransitiveType3.gen';

// tslint:disable-next-line:interface-over-type-literal
export type t2 = (null | undefined | TransitiveType3_t3);

export const convertT2: (_1:t2) => t2 = function (Arg1: any) {
  const result = TransitiveType2BS.convertT2((Arg1 == null ? undefined : [Arg1.i, Arg1.s]));
  return (result == null ? result : {i:result[0], s:result[1]})
};
