/* TypeScript file generated by genType. */

// tslint:disable-next-line:no-var-requires
const UncurriedBS = require('./Uncurried.bs');

export const uncurried0: () => string = UncurriedBS.uncurried0;

export const uncurried1: (_1:number) => string = UncurriedBS.uncurried1;

export const uncurried2: (_1:number, _2:string) => string = UncurriedBS.uncurried2;

export const uncurried3: (_1:number, _2:string, _3:number) => string = UncurriedBS.uncurried3;

export const curried3: (_1:number, _2:string, _3:number) => string = UncurriedBS.curried3;
