// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE

import * as Common$DemoSomelibrary from "@demo/somelibrary/src/Common.bs.js";

var z = Common$DemoSomelibrary.foo;

export {
  z ,
  
}
/* No side effect */
