/* TypeScript file generated by genType. */

// tslint:disable-next-line:no-var-requires
import * as UseWrapJsValueBS from './UseWrapJsValue.bs';

import {AbsoluteValue_t as WrapJsValue_AbsoluteValue_t} from './WrapJsValue.gen';

import {stringFunction as WrapJsValue_stringFunction} from './WrapJsValue.gen';

export const useGetProp: (_1:WrapJsValue_AbsoluteValue_t) => number = UseWrapJsValueBS.useGetProp;

export const useTypeImportedInOtherModule: (_1:WrapJsValue_stringFunction) => WrapJsValue_stringFunction = UseWrapJsValueBS.useTypeImportedInOtherModule;
