// Generated by BUCKLESCRIPT VERSION 4.0.7, PLEASE EDIT WITH CARE
'use strict';


function useGetProp(x) {
  return x.getProp() + 1 | 0;
}

function useTypeImportedInOtherModule(x) {
  return x;
}

exports.useGetProp = useGetProp;
exports.useTypeImportedInOtherModule = useTypeImportedInOtherModule;
/* No side effect */
