// Generated by BUCKLESCRIPT VERSION 4.0.12, PLEASE EDIT WITH CARE


function useGetProp(x) {
  return x.getProp() + 1 | 0;
}

function useTypeImportedInOtherModule(x) {
  return x;
}

export {
  useGetProp ,
  useTypeImportedInOtherModule ,
  
}
/* No side effect */
