/* TypeScript file generated by genType. */

const XX = {"ActionNoOp": -889096520, "ActionAdjustAge": 447703226, "ActionBooly": -309348007, "ActionOptionalInt": 909149433, "ActionUnity": -578879041, "ActionOptionalBooly": -1167463, "ActionOptionalBoolMapper": 6898881};

// tslint:disable-next-line:no-var-requires
const VariantsBS = require('./Variants.bs');

// tslint:disable-next-line:interface-over-type-literal
export type action = "ActionNoOp" | "ActionAdjustAge" | "ActionBooly" | "ActionOptionalInt" | "ActionUnity" | "ActionOptionalBooly" | "ActionOptionalBoolMapper";

// tslint:disable-next-line:interface-over-type-literal
export type optionalBoolMapper = {readonly optionalBoolMapper: (_1:(null | undefined | boolean)) => (null | undefined | boolean)};

export const actionToString: (_1:action) => string = function _(Arg1: any) { const result = VariantsBS.actionToString(XX[Arg1]); return result };

export const converter: (_1:optionalBoolMapper) => optionalBoolMapper = function _(Arg1: any) { const result = VariantsBS.converter([function _(Arg11: any) { const result1 = Arg1.optionalBoolMapper(Arg11); return (result1 == null ? undefined : result1) }]); return {optionalBoolMapper:function _(Arg12: any) { const result2 = result[0]((Arg12 == null ? undefined : Arg12)); return result2 }} };
