// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE


function isWeekend(x) {
  if (x !== -29784519) {
    return x === 569248848;
  } else {
    return true;
  }
}

function onlySunday(param) {
  
}

function swap(x) {
  if (x >= 569248848) {
    return /* saturday */-29784519;
  } else {
    return /* sunday */569248848;
  }
}

function testConvert(x) {
  return x;
}

function testConvert2(x) {
  return x;
}

function testConvert3(x) {
  return x;
}

function testConvert2to3(x) {
  return x;
}

function id1(x) {
  return x;
}

function id2(x) {
  return x;
}

function polyWithOpt(foo) {
  if (foo === "bar") {
    return ;
  } else if (foo !== "baz") {
    return {
            HASH: /* One */3953222,
            VAL: foo
          };
  } else {
    return {
            HASH: /* Two */4203884,
            VAL: 1
          };
  }
}

function restResult1(x) {
  return x;
}

function restResult2(x) {
  return x;
}

function restResult3(x) {
  return x;
}

var monday = /* monday */-949852400;

var saturday = /* saturday */-29784519;

var sunday = /* sunday */569248848;

var fortytwoOK = /* fortytwo */23437694;

var fortytwoBAD = /* fortytwo */23437694;

export {
  isWeekend ,
  monday ,
  saturday ,
  sunday ,
  onlySunday ,
  swap ,
  testConvert ,
  fortytwoOK ,
  fortytwoBAD ,
  testConvert2 ,
  testConvert3 ,
  testConvert2to3 ,
  id1 ,
  id2 ,
  polyWithOpt ,
  restResult1 ,
  restResult2 ,
  restResult3 ,
  
}
/* No side effect */
