// Generated by BUCKLESCRIPT VERSION 4.0.12, PLEASE EDIT WITH CARE


function actionToString(param) {
  return "";
}

function converter(x) {
  return x;
}

export {
  actionToString ,
  converter ,
  
}
/* No side effect */
