// Generated by BUCKLESCRIPT VERSION 4.0.6, PLEASE EDIT WITH CARE
'use strict';

var WrapJsValue = require("./WrapJsValue");

var roundedNumber = WrapJsValue.round(1.8);

var areaValue = WrapJsValue.area(/* record */[
      /* x */3,
      /* y */undefined
    ]);

exports.roundedNumber = roundedNumber;
exports.areaValue = areaValue;
/* roundedNumber Not a pure module */
