// Generated by BUCKLESCRIPT VERSION 4.0.11, PLEASE EDIT WITH CARE

import * as WrapJsValueGen from "./WrapJsValue.gen";

var roundedNumber = WrapJsValueGen.round(1.8);

var areaValue = WrapJsValueGen.area(/* record */[
      /* x */3,
      /* y */undefined
    ]);

function getAbs(x) {
  return x.getAbs();
}

var AbsoluteValue = /* module */[/* getAbs */getAbs];

function useGetProp(x) {
  return x.getProp() + 1 | 0;
}

function useGetAbs(x) {
  return x.getAbs() + 1 | 0;
}

export {
  roundedNumber ,
  areaValue ,
  AbsoluteValue ,
  useGetProp ,
  useGetAbs ,
  
}
/* roundedNumber Not a pure module */
