// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE

import * as List from "bs-platform/lib/es6/list.js";
import * as React from "react";
import * as ReasonReact from "reason-react/src/ReasonReact.js";

var component = ReasonReact.statelessComponent("Page");

function handleClick(_event, _self) {
  console.log("clicked!");
  
}

function Component1(Props) {
  var messageOpt = Props.message;
  var message = messageOpt !== undefined ? messageOpt : "default message";
  return React.createElement("div", undefined, message);
}

function plus(x, _y) {
  return x + 1 | 0;
}

function concat(x, y) {
  if (y !== undefined) {
    return x + y;
  }
  
}

function consumeVariant(x) {
  if (typeof x === "number") {
    return 1;
  }
  if (!x.TAG) {
    return (x._0 + x._1 | 0) + 2 | 0;
  }
  var n = x._0;
  return (
          n !== undefined ? n : 0
        ) + 3 | 0;
}

var make = Component1;

var l = {
  hd: 1,
  tl: {
    hd: 2,
    tl: {
      hd: 3,
      tl: /* [] */0
    }
  }
};

var map = List.map;

export {
  component ,
  handleClick ,
  make ,
  plus ,
  concat ,
  consumeVariant ,
  l ,
  map ,
  
}
/* component Not a pure module */
