// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE

import * as List from "bs-platform/lib/es6/list.js";
import * as Curry from "bs-platform/lib/es6/curry.js";
import * as React from "react";
import * as ReasonReact from "reason-react/src/ReasonReact.js";

var component = ReasonReact.statelessComponent("Page");

function handleClick(_event, _self) {
  console.log("clicked!");
  
}

function make(messageOpt, _children) {
  var message = messageOpt !== undefined ? messageOpt : "default message";
  return {
          debugName: component.debugName,
          reactClassInternal: component.reactClassInternal,
          handedOffState: component.handedOffState,
          willReceiveProps: component.willReceiveProps,
          didMount: component.didMount,
          didUpdate: component.didUpdate,
          willUnmount: component.willUnmount,
          willUpdate: component.willUpdate,
          shouldUpdate: component.shouldUpdate,
          render: (function (self) {
              return React.createElement("div", {
                          onClick: Curry._1(self.handle, handleClick)
                        }, message);
            }),
          initialState: component.initialState,
          retainedProps: component.retainedProps,
          reducer: component.reducer,
          jsElementWrapped: component.jsElementWrapped
        };
}

function plus(x, _y) {
  return x + 1 | 0;
}

function concat(x, y) {
  if (y !== undefined) {
    return x + y;
  }
  
}

function consumeVariant(x) {
  if (typeof x === "number") {
    return 1;
  }
  if (!x.tag) {
    return (x[0] + x[1] | 0) + 2 | 0;
  }
  var n = x[0];
  return (
          n !== undefined ? n : 0
        ) + 3 | 0;
}

var l = /* :: */[
  1,
  /* :: */[
    2,
    /* :: */[
      3,
      /* [] */0
    ]
  ]
];

var map = List.map;

export {
  component ,
  handleClick ,
  make ,
  plus ,
  concat ,
  consumeVariant ,
  l ,
  map ,
  
}
/* component Not a pure module */
