// Generated by BUCKLESCRIPT VERSION 5.0.6, PLEASE EDIT WITH CARE

import * as ImportHookDefaultGen from "./ImportHookDefault.gen";

var make = ImportHookDefaultGen.make;

export {
  make ,
  
}
/* make Not a pure module */
