// Generated by BUCKLESCRIPT VERSION 4.0.17, PLEASE EDIT WITH CARE

import * as Component1 from "./Component1.bs.js";
import * as Component2 from "./Component2.bs.js";
import * as ReactDOMRe from "reason-react/src/ReactDOMRe.js";
import * as ReasonReact from "reason-react/src/ReasonReact.js";

ReactDOMRe.renderToElementWithId(ReasonReact.element(undefined, undefined, Component1.make("Hello!", /* array */[])), "index1");

ReactDOMRe.renderToElementWithId(ReasonReact.element(undefined, undefined, Component2.make("Hello!", /* array */[])), "index2");

export {
  
}
/*  Not a pure module */
