// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import * as Component2 from "./Component2.bs.js";
import * as ReactDOMRe from "reason-react/src/legacy/ReactDOMRe.bs.js";

ReactDOMRe.renderToElementWithId(React.createElement(Component2.make, {
          greeting: "Hello!"
        }), "index2");

export {
  
}
/*  Not a pure module */
