// Generated by BUCKLESCRIPT VERSION 5.0.6, PLEASE EDIT WITH CARE


var Wrapper = /* module */[];

var Wrapper2 = /* module */[/* Wrapper */Wrapper];

var A = /* module */[];

var M2 = /* module */[/* M1 */A];

var M3 = /* module */[/* M2 */M2];

export {
  Wrapper2 ,
  A ,
  M3 ,
  
}
/* No side effect */
