// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE


function foo(x) {
  return x;
}

function useProps(props) {
  return props.foo + 1 | 0;
}

function usePropsClosed(props) {
  return props.fooClosed + 1 | 0;
}

export {
  foo ,
  useProps ,
  usePropsClosed ,
  
}
/* No side effect */
