// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Belt_Option from "rescript/lib/es6/belt_Option.js";
import * as Caml_option from "rescript/lib/es6/caml_option.js";

function computeArea(param) {
  return Math.imul(Math.imul(param.x, param.y), Belt_Option.mapWithDefault(param.z, 1, (function (n) {
                    return n;
                  })));
}

function coord2d(x, y) {
  return {
          x: x,
          y: y,
          z: undefined
        };
}

function computeArea2(param) {
  return Math.imul(Math.imul(param.a, param.b), Belt_Option.mapWithDefault(Caml_option.nullable_to_opt(param.c), 1, (function (n) {
                    return n;
                  })));
}

function computeArea3(o) {
  return Math.imul(Math.imul(o.x, o.y), Belt_Option.mapWithDefault(Caml_option.nullable_to_opt(o.z), 1, (function (n) {
                    return n;
                  })));
}

function computeArea4(o) {
  return Math.imul(Math.imul(o.x, o.y), Belt_Option.mapWithDefault(o.z, 1, (function (n) {
                    return n;
                  })));
}

function computeNested(param) {
  return 0;
}

function computeNestedNested(param) {
  return 0;
}

function computeNestedNestedNullable(param) {
  return 0;
}

function computeNestedNestedHalfNullable(param) {
  return 0;
}

function useTypeImportedInOtherModule(x) {
  return x;
}

function convertInner(x) {
  return x;
}

function convertOuter(x) {
  return x;
}

function testMyRecBsAs(x) {
  return [
          x.jsValid0,
          x.type,
          x["the-key"],
          x["with\"dquote"],
          x["with'squote"],
          x["1number"]
        ];
}

function testMyRecBsAs2(x) {
  return x;
}

var origin = {
  x: 0,
  y: 0,
  z: 0
};

export {
  origin ,
  computeArea ,
  coord2d ,
  computeArea2 ,
  computeArea3 ,
  computeArea4 ,
  computeNested ,
  computeNestedNested ,
  computeNestedNestedNullable ,
  computeNestedNestedHalfNullable ,
  useTypeImportedInOtherModule ,
  convertInner ,
  convertOuter ,
  testMyRecBsAs ,
  testMyRecBsAs2 ,
  
}
/* No side effect */
