// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE


var M = {
  a: 34
};

var shadowed = 6;

var num = 35;

var Nested = {
  offset: 1,
  M: M,
  height: 1,
  shadowed: shadowed,
  num: num
};

export {
  Nested ,
  
}
/* No side effect */
