// Generated by ReScript, PLEASE EDIT WITH CARE

import * as TestImportGen from "./TestImport.gen";

var innerStuffContents = TestImportGen.innerStuffContents;

var innerStuffContentsAsEmptyObject = TestImportGen.innerStuffContentsAsEmptyObject;

var valueStartingWithUpperCaseLetter = TestImportGen.valueStartingWithUpperCaseLetter;

var defaultValue = TestImportGen.defaultValue;

function make(prim0, prim1, prim2) {
  return TestImportGen.make(prim0, prim1, prim2);
}

export {
  innerStuffContentsAsEmptyObject ,
  innerStuffContents ,
  valueStartingWithUpperCaseLetter ,
  defaultValue ,
  make ,
  
}
/* innerStuffContents Not a pure module */
