// Generated by BUCKLESCRIPT VERSION 5.0.0-dev.6, PLEASE EDIT WITH CARE

import * as TestImportGen from "./TestImport.gen";
import * as ImportMyBannerGen from "./ImportMyBanner.gen";

var innerStuffContents = TestImportGen.innerStuffContents;

function make(prim, prim$1, prim$2) {
  return ImportMyBannerGen.make(prim, prim$1, prim$2);
}

export {
  innerStuffContents ,
  make ,
  
}
/* innerStuffContents Not a pure module */
