// Generated by BUCKLESCRIPT VERSION 6.0.0-dev.1, PLEASE EDIT WITH CARE


function testConversion(x) {
  return x;
}

var A = /* module */[];

export {
  testConversion ,
  A ,
  
}
/* No side effect */
