// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE


function uncurried0() {
  return "";
}

function uncurried1(x) {
  return String(x);
}

function uncurried2(x, y) {
  return String(x) + y;
}

function uncurried3(x, y, z) {
  return String(x) + (y + String(z));
}

function curried3(x, y, z) {
  return String(x) + (y + String(z));
}

export {
  uncurried0 ,
  uncurried1 ,
  uncurried2 ,
  uncurried3 ,
  curried3 ,
  
}
/* No side effect */
