/* TypeScript file generated by genType. */

// tslint:disable-next-line:no-var-requires
import * as ManyComponentsBS from './ManyComponents.bs';

// tslint:disable-next-line:no-var-requires
import * as ReasonReact from 'reason-react/src/ReasonReact.js';

// tslint:disable-next-line:interface-over-type-literal
export type InnerComponent_Props = {readonly children?: unknown};

export const InnerComponent: React.ComponentClass<InnerComponent_Props> = ReasonReact.wrapReasonForJs(
  ManyComponentsBS.component,
  (function _(jsProps: InnerComponent_Props) {
     return ManyComponentsBS.make(jsProps.children);
  }));

// tslint:disable-next-line:interface-over-type-literal
export type Props = {readonly children?: unknown};

export const ManyComponents: React.ComponentClass<Props> = ReasonReact.wrapReasonForJs(
  ManyComponentsBS.component,
  (function _(jsProps: Props) {
     return ManyComponentsBS.make(jsProps.children);
  }));

export default ManyComponents;
