/* Typescript file generated by genType. */

// tslint:disable-next-line:no-var-requires
const ManyComponentsBS = require('./ManyComponents.bs');

// tslint:disable-next-line:no-var-requires
const ReasonReact = require('reason-react/src/ReasonReact.js');

// tslint:disable-next-line:interface-over-type-literal
export type Props = {children?: unknown};

export const InnerComponent: React.ComponentClass<Props> = ReasonReact.wrapReasonForJs(
  ManyComponentsBS.component,
  (function _(jsProps: Props) {
     return ManyComponentsBS.make(jsProps.children);
  }));

// tslint:disable-next-line:interface-over-type-literal
export type Props2 = {children?: unknown};

export const ManyComponents: React.ComponentClass<Props2> = ReasonReact.wrapReasonForJs(
  ManyComponentsBS.component,
  (function _(jsProps: Props2) {
     return ManyComponentsBS.make(jsProps.children);
  }));

export default ManyComponents;
