/* TypeScript file generated by genType. */

// tslint:disable-next-line:no-var-requires
const Curry = require('bs-platform/lib/es6/curry.js');

// tslint:disable-next-line:no-var-requires
const ManyComponentsBS = require('./ManyComponents.bs');

// tslint:disable-next-line:no-var-requires
const ReasonReact = require('reason-react/src/ReasonReact.js');

// tslint:disable-next-line:interface-over-type-literal
export type InnerComponent_Props = {readonly children?: unknown};

export const InnerComponent: React.ComponentClass<InnerComponent_Props> = ReasonReact.wrapReasonForJs(
  ManyComponentsBS.InnerComponent[1],
  (function _(jsProps: InnerComponent_Props) {
     return ManyComponentsBS.InnerComponent[2](jsProps.children);
  }));

// tslint:disable-next-line:interface-over-type-literal
export type ManyProps_Props = {
  readonly a: unknown, 
  readonly b: unknown, 
  readonly c: unknown, 
  readonly d: unknown, 
  readonly e: unknown, 
  readonly f: unknown, 
  readonly g: unknown, 
  readonly h: unknown, 
  readonly children?: unknown
};

export const ManyProps: React.ComponentClass<ManyProps_Props> = ReasonReact.wrapReasonForJs(
  ManyComponentsBS.ManyProps[0],
  (function _(jsProps: ManyProps_Props) {
     return Curry.app(ManyComponentsBS.ManyProps[1], [jsProps.a, jsProps.b, jsProps.c, jsProps.d, jsProps.e, jsProps.f, jsProps.g, jsProps.h, jsProps.children]);
  }));

// tslint:disable-next-line:interface-over-type-literal
export type Props = {readonly children?: unknown};

export const ManyComponents: React.ComponentClass<Props> = ReasonReact.wrapReasonForJs(
  ManyComponentsBS.component,
  (function _(jsProps: Props) {
     return ManyComponentsBS.make(jsProps.children);
  }));

export default ManyComponents;
