// Generated by BUCKLESCRIPT VERSION 4.0.6, PLEASE EDIT WITH CARE
'use strict';


function isWeekend(x) {
  if (x !== -29784519) {
    return x === 569248848;
  } else {
    return true;
  }
}

function onlySunday() {
  return /* () */0;
}

function swap(x) {
  if (x >= 569248848) {
    return /* saturday */-29784519;
  } else {
    return /* sunday */569248848;
  }
}

function testConvert(x) {
  return x;
}

function testConvert2(x) {
  return x;
}

function testConvert3(x) {
  return x;
}

var monday = /* monday */-949852400;

var saturday = /* saturday */-29784519;

var sunday = /* sunday */569248848;

var fortytwoOK = /* fortytwo */23437694;

var fortytwoBAD = /* fortytwo */23437694;

exports.isWeekend = isWeekend;
exports.monday = monday;
exports.saturday = saturday;
exports.sunday = sunday;
exports.onlySunday = onlySunday;
exports.swap = swap;
exports.testConvert = testConvert;
exports.fortytwoOK = fortytwoOK;
exports.fortytwoBAD = fortytwoBAD;
exports.testConvert2 = testConvert2;
exports.testConvert3 = testConvert3;
/* No side effect */
