// Generated by BUCKLESCRIPT VERSION 4.0.6, PLEASE EDIT WITH CARE
'use strict';

var Curry = require("bs-platform/lib/js/curry.js");
var Belt_Option = require("bs-platform/lib/js/belt_Option.js");
var SomeFlowTypes = require("./SomeFlowTypes");

function consumeOption(x) {
  return Belt_Option.mapWithDefault(x, 0, (function (n) {
                return n;
              }));
}

function consumeOption2(x) {
  return Belt_Option.mapWithDefault(x, 0, (function (n) {
                return n;
              }));
}

function testArray(a) {
  return a;
}

function identity(x) {
  return x;
}

function isWeekend(day) {
  if (day === SomeFlowTypes.SATURDAY) {
    return true;
  } else {
    return day === SomeFlowTypes.SUNDAY;
  }
}

function testFunctionOnOptionsAsArgument(a, foo) {
  return Curry._1(foo, a);
}

exports.consumeOption = consumeOption;
exports.consumeOption2 = consumeOption2;
exports.testArray = testArray;
exports.identity = identity;
exports.isWeekend = isWeekend;
exports.testFunctionOnOptionsAsArgument = testFunctionOnOptionsAsArgument;
/* ./SomeFlowTypes Not a pure module */
