// Generated by BUCKLESCRIPT VERSION 4.0.6, PLEASE EDIT WITH CARE
'use strict';

var Belt_Option = require("bs-platform/lib/js/belt_Option.js");
var SomeFlowTypes = require("./SomeFlowTypes");

function consumeOption(x) {
  return Belt_Option.mapWithDefault(x, 0, (function (n) {
                return n;
              }));
}

function consumeOption2(x) {
  return Belt_Option.mapWithDefault(x, 0, (function (n) {
                return n;
              }));
}

function testArray(a) {
  return a;
}

function identity(x) {
  return x;
}

function isWeekend(day) {
  if (day === SomeFlowTypes.SATURDAY) {
    return true;
  } else {
    return day === SomeFlowTypes.SUNDAY;
  }
}

function isWeekend$1() {
  return true;
}

function onlySunday() {
  return /* () */0;
}

var Poly = /* module */[
  /* isWeekend */isWeekend$1,
  /* monday : monday */-949852400,
  /* saturday : saturday */-29784519,
  /* sunday : sunday */569248848,
  /* onlySunday */onlySunday
];

exports.consumeOption = consumeOption;
exports.consumeOption2 = consumeOption2;
exports.testArray = testArray;
exports.identity = identity;
exports.isWeekend = isWeekend;
exports.Poly = Poly;
/* ./SomeFlowTypes Not a pure module */
