// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE


function DynamicallyLoadedComponent(Props) {
  return Props.s;
}

var make = DynamicallyLoadedComponent;

export {
  make ,
  
}
/* No side effect */
