// Generated by BUCKLESCRIPT VERSION 4.0.7, PLEASE EDIT WITH CARE
'use strict';

var MyBannerWrapperRegen = require("./MyBannerWrapper.regen");

function make(prim, prim$1, prim$2) {
  return MyBannerWrapperRegen.make(prim, prim$1, prim$2);
}

exports.make = make;
/* ./MyBannerWrapper.regen Not a pure module */
