// Generated by BUCKLESCRIPT VERSION 4.0.6, PLEASE EDIT WITH CARE
'use strict';

var MyBannerReRe = require("./MyBannerRe.re");

function make(prim, prim$1, prim$2) {
  return MyBannerReRe.make(prim, prim$1, prim$2);
}

exports.make = make;
/* ./MyBannerRe.re Not a pure module */
