// Generated by BUCKLESCRIPT VERSION 4.0.6, PLEASE EDIT WITH CARE
'use strict';

var TestRe = require("./Test.re");

var roundedNumber = TestRe.round(1.8);

console.log("Test.re roundedNumber:", roundedNumber);

exports.roundedNumber = roundedNumber;
/* roundedNumber Not a pure module */
