// Generated by BUCKLESCRIPT VERSION 4.0.7, PLEASE EDIT WITH CARE
'use strict';

var WrapJsValueGen = require("./WrapJsValue.gen");

function myArea(prim) {
  return WrapJsValueGen.area(prim);
}

var roundedNumber = WrapJsValueGen.round(1.8);

var areaValue = WrapJsValueGen.area(/* record */[
      /* x */3,
      /* y */undefined
    ]);

exports.myArea = myArea;
exports.roundedNumber = roundedNumber;
exports.areaValue = areaValue;
/* roundedNumber Not a pure module */
