// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE

import * as Common$DemoSomeLibrary from "@demo/some-library/src/Common.bs.js";

var z = Common$DemoSomeLibrary.foo;

export {
  z ,
  
}
/* No side effect */
